language: node_js
node_js:
- '7'
before_deploy:
  - npm run deploy
  - cp .gitignore_deploy .gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
