language: node_js
node_js:
- '7'
before_deploy: npm run deploy
deploy:
  provider: heroku
  api_key:
    secure: APpoiUxXSXEYzQXo8PWxpUB/b85ZTiqkxGwRq/mQkdsIY62G8fBSsb6hbQM+ijhgMjW1JaQ38LNeBFpX8KTuY9vOxzG7EvkOE+EjgR8hzbVaZFyK6ySZ+nr9f/PGQxlnrewBOi1ojscxg7YP7GPccaCMG8LZgjvvYARaFbgjIEl0n0mFqus7qIcJHR94bkuOj2VuTnH/Le0xlrb9kW9UMaaRcM+Vw573/HmflRDOC9EWCb4Jcpte/D9rxLcxILP5yVLAtwO5UONV83zGiZ9kMuLFFvRAheennfTApmNV5J06hFTmDI/owUoACM2MZLF2pe2kwIRUkf4zJpa9jEL3f2wLph9pf94LI0Gk5lCbZw5nvmlEWoMtAAQ5uubyAzyeFyyrC8DAW1G/gSMA9zS+6LPRPan8+iLc5+e2aeSLV7/S4Tt+jKyyz4qgzidXc338u9ni2NynTDlpn/FfV49XRa9z0/F8wTuH3PYbCfCtHX7Qs8ifHgYA/GlPBh99v++l6bA11W/zM55PupKg9aKVfEUqJmGvSl48MInz982yljgsmpL/7G3XJfnxOD1+XuVQrXfXCF2tALnUz+8LBc5rfA0PlPOnofmarnsMAPKD2SiTngSiT/uK1bQYyeXV7Nv6EEuSh4srIyGyrayb+Jhgc2iUWv5pzrm4uY2XwBM0irs=
  app: l10y
  skip_cleanup: true
  on:
    branch: master
